-- Seed data generated by Chat GPT

-- Seed data for users table
INSERT INTO users (first_name, last_name, username, email, hashed_password, status)
VALUES ('John', 'Doe', 'johndoe', 'john.doe@example.com', 'hashed_password_1', 'active'),
       ('Jane', 'Doe', 'janedoe', 'jane.doe@example.com', 'hashed_password_2', 'active'),
       ('Alice', 'Smith', 'alicesmith', 'alice.smith@example.com', 'hashed_password_3', 'active'),
       ('Bob', 'Johnson', 'bobjohnson', 'bob.johnson@example.com', 'hashed_password_4', 'active'),
       ('Charlie', 'Brown', 'charliebrown', 'charlie.brown@example.com', 'hashed_password_5', 'active'),
       ('Eve', 'White', 'evewhite', 'eve.white@example.com', 'hashed_password_6', 'active'),
       ('Mallory', 'Black', 'malloryblack', 'mallory.black@example.com', 'hashed_password_7', 'active'),
       ('Trent', 'Green', 'trentgreen', 'trent.green@example.com', 'hashed_password_8', 'active'),
       ('Trudy', 'Blue', 'trudyblue', 'trudy.blue@example.com', 'hashed_password_9', 'active'),
       ('Walter', 'Gray', 'waltergray', 'walter.gray@example.com', 'hashed_password_10', 'active');

-- Seed data for games table
INSERT INTO games (title, description, release_date, genre, studio, game_api_id)
VALUES ('Game 1', 'An amazing game 1', '2022-01-01', 'Action', 'Studio 1', 1001),
       ('Game 2', 'An amazing game 2', '2022-01-02', 'Adventure', 'Studio 1', 1002),
       ('Game 3', 'An amazing game 3', '2022-01-03', 'RPG', 'Studio 2', 1003),
       ('Game 4', 'An amazing game 4', '2022-01-04', 'Strategy', 'Studio 2', 1004),
       ('Game 5', 'An amazing game 5', '2022-01-05', 'Simulation', 'Studio 3', 1005),
       ('Game 6', 'An amazing game 6', '2022-01-06', 'Sports', 'Studio 3', 1006),
       ('Game 7', 'An amazing game 7', '2022-01-07', 'Racing', 'Studio 4', 1007),
       ('Game 8', 'An amazing game 8', '2022-01-08', 'Puzzle', 'Studio 4', 1008),
       ('Game 9', 'An amazing game 9', '2022-01-09', 'Platformer', 'Studio 5', 1009),
       ('Game 10', 'An amazing game 10', '2022-01-10', 'FPS', 'Studio 5', 1010);

-- Seed data for favorite_games table
INSERT INTO favorite_games (user_id, game_id)
VALUES (1, 1), (1, 2), (2, 3), (2, 4), (3, 5), (3, 6), (4, 7), (4, 8), (5, 9), (5, 10), (6, 1), (6, 2), (7, 3), (7, 4), (8, 5), (8, 6), (9, 7), (10, 8);

-- Seed data for reviews table
INSERT INTO reviews (content, rating, user_id, game_id)
VALUES ('Great game!', 5, 1, 1), ('Could be better.', 3, 2, 1), ('Loved it!', 4.5, 3, 2),
       ('Disappointing.', 2, 4, 2), ('Fantastic!', 4.7, 5, 3), ('Not my cup of tea.', 2.5, 6, 3),
       ('Excellent gameplay.', 4.8, 7, 4), ('Meh.', 3, 8, 4), ('So addictive!', 4.9, 9, 5),
       ('Needs improvement.', 2.7, 10, 5);

-- Seed data for user_followers table
INSERT INTO user_followers (user_id, follower_id)
VALUES (1, 2), (1, 3), (1, 4), (1, 5), (2, 6), (2, 7), (3, 8), (3, 9), (4, 10), (5, 1);

-- Seed data for posts table
INSERT INTO posts (content, user_id)
VALUES ('Just started playing Game 1!', 1), ('Finished Game 2, what a journey.', 2),
       ('Game 3 is so immersive.', 3), ('I didnt like Game 4 much.', 4),
       ('Game 5 is my new favorite!', 5), ('Game 6 was disappointing.', 6),
       ('I highly recommend Game 7.', 7), ('Game 8 is too hard.', 8),
       ('Game 9 is incredibly fun.', 9), ('Cant wait for Game 10!', 10);

-- Seed data for post_likes table
INSERT INTO post_likes (post_id, user_id)
VALUES (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10), (10, 1);

-- Seed data for comments table
INSERT INTO comments (content, user_id, post_id)
VALUES ('I loved that game too!', 2, 1), ('I agree, it was fantastic.', 3, 2),
       ('The story was so engaging.', 4, 3), ('I found it boring.', 5, 4),
       ('I cant put it down!', 6, 5), ('They should fix the bugs.', 7, 6),
       ('The graphics are amazing.', 8, 7), ('Keep trying, it gets easier!', 9, 8),
       ('The levels are so creative.', 10, 9), ('Me too, its gonna be epic!', 1, 10);

-- Seed data for groups table
-- Seed data for groups table
INSERT INTO groups (name, description, date_created, game_id, owner_id)
VALUES ("Game 1 Fans", "A group for fans of Game 1", '2022-01-15', 1, 1),
       ("Game 2 Lovers", "A group for fans of Game 2", '2022-02-10', 2, 2),
       ("Game 3 Enthusiasts", "A group for fans of Game 3", '2022-03-05', 3, 3),
       ("Game 4 Club", "A group for fans of Game 4", '2022-04-01', 4, 4),
       ("Game 5 Mania", "A group for fans of Game 5", '2022-05-15', 5, 5),
       ("Game 6 Players", "A group for fans of Game 6", '2022-06-08', 6, 6),
       ("Game 7 Community", "A group for fans of Game 7", '2022-07-10', 7, 7),
       ("Game 8 Fans", "A group for fans of Game 8", '2022-08-20', 8, 8),
       ("Game 9 Guild", "A group for fans of Game 9", '2022-09-01', 9, 9),
       ("Game 10 Devotees", "A group for fans of Game 10", '2022-10-15', 10, 10);

-- Seed data for group_users table
INSERT INTO group_users (group_id, user_id)
VALUES (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10);


